#!/bin/bash

# Update the package list
sudo apt-get update

# Install Apache
sudo apt-get install apache2 -y

# Install MySQL
sudo apt-get install mysql-server -y

# Install PHP
sudo apt-get install php libapache2-mod-php php-mysql -y

# Restart Apache
sudo service apache2 restart
